Add support for log streams
Yimura/AsyncLogger pull request #3
Opened 2024-06-06 02:18 UTC by maybegreat48

2024-06-08 15:52 UTC, Yimura requested changes
Mixed indents here and there.

Could you give an example of how usage of this feature would look like in-code?

2024-06-08 15:52 UTC, Yimura commented on src/LogStream.hpp
> +		void* m_UserData;
What's the usage of this?

2024-06-08 19:46 UTC, maybegreat48 commented on src/LogStream.hpp
> +		void* m_UserData;
Clients can add an userdata (pointer to anything) that they can later retrieve at the sink

2024-06-21 13:07 UTC, xiaoxiao921 requested changes

2024-06-21 13:07 UTC, xiaoxiao921 commented on include/AsyncLogger/Logger.hpp
> +#if !defined(USE_FMT) && CXX_FORMAT_SUPPORT || true
Such hack not needed when add_compile_definitions(CXX_FORMAT_SUPPORT) is properly defined

2024-06-24 12:41 UTC, merged